import type { LiteraturePeriodId, LiteratureWork, Source } from "@/types/content";

export const LITERATURE_PAGE_META = {
  seoTitle: "Nigeria in Literature",
  seoDescription:
    "Novels, memoirs, biographies, plays, and films that picture Nigerian eras, each with a verified publication claim and a named source.",
  eyebrow: "Culture",
  title: "Nigeria in Literature",
  description:
    "Novels, memoirs, plays, and films that picture Nigerian eras. Each claim is sourced. Portraits come from Icons; covers are typographic plates.",
  filterAll: "All periods",
  mediumAll: "All media",
  sourcesNote: "Open a source to check the claim independently.",
  verifiedLabel: "Verified:",
  sourcesToggle: (count: number) => (count === 1 ? "1 source" : `${count} sources`),
  portraitCredit: "Portrait",
  emptyFilter: "No works in that filter yet.",
  railEarliestLabel: "Earliest here",
  railMemoirsLabel: "Memoirs",
  railBooksLabel: "Books & plays",
  railFilmsLabel: "Films",
  railFallbackYear: "1947",
  railFallbackEarliestId: "path-to-nigerian-freedom",
  railMemoirsHref: "#awo-autobiography",
  railBooksHref: "#things-fall-apart",
  railFilmsHref: "#living-in-bondage",
} as const;

export const LITERATURE_PERIODS: {
  id: LiteraturePeriodId;
  label: string;
  blurb: string;
}[] = [
  {
    id: "oral-to-print",
    label: "Oral into print",
    blurb: "Yoruba story logic meeting London publishers.",
  },
  {
    id: "colonial-encounter",
    label: "Colonial encounter",
    blurb: "Village authority meeting mission and empire.",
  },
  {
    id: "independence",
    label: "Independence decades",
    blurb: "Cities, gender, and the first republic’s long shadow.",
  },
  {
    id: "civil-war",
    label: "Civil War",
    blurb: "Biafra remembered in fiction and memoir.",
  },
  {
    id: "military-allegory",
    label: "Military allegory",
    blurb: "Power, ritual, and the talking drum as politics.",
  },
  {
    id: "leaders-memory",
    label: "Leaders in their words",
    blurb: "Autobiographies and close biographies of heads of state and nation-builders.",
  },
  {
    id: "video-boom",
    label: "Video boom",
    blurb: "Igbo-language VHS that scaled a national industry.",
  },
  {
    id: "contemporary",
    label: "Contemporary",
    blurb: "Returnee novels, Lagos power cinema, and streaming-era myth.",
  },
];

export const LITERATURE_MEDIUM_LABELS: Record<LiteratureWork["medium"], string> = {
  book: "Book",
  memoir: "Memoir",
  biography: "Biography",
  play: "Play",
  film: "Film",
  series: "Series",
};

/** Bibliographic and trade sources for literature claims. */
export const LITERATURE_SOURCES: Source[] = [
  {
    id: "lit-faber-palm-wine-drinkard",
    title: "The Palm-Wine Drinkard",
    publisher: "Faber and Faber",
    year: 1952,
    url: "https://www.faber.co.uk/product/9780571311538-the-palm-wine-drinkard/",
    accessedAt: "2026-10-06",
    eras: ["independence"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-britannica-achebe",
    title: "Chinua Achebe",
    publisher: "Encyclopaedia Britannica",
    year: 2024,
    url: "https://www.britannica.com/biography/Chinua-Achebe",
    accessedAt: "2026-10-06",
    eras: ["independence"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-bbc-soyinka-horseman",
    title: "This Wole Soyinka play showed the future of English",
    publisher: "BBC Culture",
    year: 2018,
    url: "https://www.bbc.com/culture/article/20180509-this-wole-soyinka-play-showed-the-future-of-english",
    accessedAt: "2026-10-06",
    eras: ["colonial", "independence"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-caval-joys-motherhood",
    title: "The joys of motherhood : a novel",
    publisher: "Allison & Busby (catalogue record via CAVAL)",
    year: 1979,
    url: "https://folio.caval.edu.au/Record/c000033628",
    accessedAt: "2026-10-06",
    eras: ["independence"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-booker-famished-road",
    title: "The Famished Road",
    publisher: "The Booker Prizes",
    year: 1991,
    url: "https://thebookerprizes.com/the-booker-library/books/the-famished-road",
    accessedAt: "2026-10-06",
    eras: ["military-rule"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-britannica-living-in-bondage",
    title: "Living in Bondage",
    publisher: "Encyclopaedia Britannica",
    year: 2024,
    url: "https://www.britannica.com/topic/Living-in-Bondage",
    accessedAt: "2026-10-06",
    eras: ["democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-aff-saworoide",
    title: "Saworoide / Brass Bells",
    publisher: "African Film Festival, Inc.",
    year: 1999,
    url: "https://africanfilmny.org/films/saworoide-brass-bells/",
    accessedAt: "2026-10-06",
    eras: ["military-rule", "democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-algonquin-purple-hibiscus",
    title: "Purple Hibiscus",
    publisher: "Algonquin Books / Hachette Book Group",
    year: 2003,
    url: "https://www.hachettebookgroup.com/titles/chimamanda-ngozi-adichie/purple-hibiscus/9781616202415/?lens=algonquin-books",
    accessedAt: "2026-10-06",
    eras: ["democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-fourth-estate-half-yellow-sun",
    title: "Half of a Yellow Sun",
    publisher: "4th Estate",
    year: 2006,
    url: "https://www.4thestate.co.uk/products/half-of-a-yellow-sun-chimamanda-ngozi-adichie-9780007200276/",
    accessedAt: "2026-10-06",
    eras: ["civil-war"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-knopf-americanah",
    title: "Americanah",
    publisher: "Penguin Random House (Knopf)",
    year: 2013,
    url: "https://prhinternationalsales.com/book/?isbn=9780307271082",
    accessedAt: "2026-10-06",
    eras: ["democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-variety-lionheart",
    title: "Toronto: Netflix Buys Nigerian Comedy Movie ‘Lionheart’",
    publisher: "Variety",
    year: 2018,
    url: "https://variety.com/2018/film/news/toronto-netflix-nigerian-comedy-movie-lionheart-1202932393/",
    accessedAt: "2026-10-06",
    eras: ["democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-guardian-king-of-boys",
    title: "Kemi Adetiba’s Gripping New Film, King Of Boys, Set To Hit Cinemas Friday 26 October",
    publisher: "The Guardian Nigeria",
    year: 2018,
    url: "https://guardian.ng/life/kemi-adetibas-gripping-new-film-king-of-boys-set-to-hit-cinemas-friday-26-october/",
    accessedAt: "2026-10-06",
    eras: ["democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-netflix-anikulapo",
    title: "Aníkúlápó",
    publisher: "Netflix",
    year: 2022,
    url: "https://www.netflix.com/title/81392197",
    accessedAt: "2026-10-06",
    eras: ["pre-colonial", "democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-bbfc-anikulapo",
    title: "Anikulapo classification record",
    publisher: "British Board of Film Classification",
    year: 2022,
    url: "https://www.bbfc.co.uk/release/anikulapo-q29sbgvjdglvbjpwwc0xmda4mdqw",
    accessedAt: "2026-10-06",
    eras: ["pre-colonial", "democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-britannica-path-nigerian-freedom",
    title: "Path to Nigerian Freedom",
    publisher: "Encyclopaedia Britannica",
    year: 2024,
    url: "https://www.britannica.com/topic/Path-to-Nigerian-Freedom",
    accessedAt: "2026-10-06",
    eras: ["colonial", "independence"],
    sectors: ["governance", "creative-economy"],
  },
  {
    id: "lit-africabib-path-nigerian-freedom",
    title: "Path to Nigerian freedom",
    publisher: "AfricaBib / Faber and Faber catalogue record",
    year: 1947,
    url: "https://www.africabib.org/rec.php?RID=107878070",
    accessedAt: "2026-10-06",
    eras: ["colonial"],
    sectors: ["governance"],
  },
  {
    id: "lit-archive-awo",
    title: "The Autobiography of Chief Obafemi Awolowo",
    publisher: "Internet Archive (Cambridge University Press, 1960)",
    year: 1960,
    url: "https://archive.org/details/autobiographyofc0000camb",
    accessedAt: "2026-10-06",
    eras: ["independence"],
    sectors: ["governance"],
  },
  {
    id: "lit-abebooks-awo",
    title: "Awo: The Autobiography of Chief Obafemi Awolowo",
    publisher: "AbeBooks listing (Cambridge University Press, 1960)",
    year: 1960,
    url: "https://www.abebooks.com/first-edition/Awo-Autobiography-Chief-Obafemi-Awolowo-Cambridge/31628119956/bd",
    accessedAt: "2026-10-06",
    eras: ["independence"],
    sectors: ["governance"],
  },
  {
    id: "lit-nla-my-command",
    title: "My command : an account of the Nigerian civil war 1967-1970",
    publisher: "National Library of Australia catalogue (Heinemann, 1980)",
    year: 1980,
    url: "https://catalogue.nla.gov.au/catalog/1692538",
    accessedAt: "2026-10-06",
    eras: ["civil-war"],
    sectors: ["governance", "security"],
  },
  {
    id: "lit-nla-why-we-struck",
    title: "Why we struck : the story of the first Nigerian coup",
    publisher: "National Library of Australia catalogue (Evans Brothers, 1981)",
    year: 1981,
    url: "https://catalogue.nla.gov.au/catalog/733328",
    accessedAt: "2026-10-06",
    eras: ["first-republic", "military-rule"],
    sectors: ["governance", "security"],
  },
  {
    id: "lit-penguin-there-was-a-country",
    title: "There Was a Country",
    publisher: "Penguin Books UK",
    year: 2012,
    url: "https://www.penguin.co.uk/books/183886/there-was-a-country-by-achebe-chinua/9780141973678",
    accessedAt: "2026-10-06",
    eras: ["civil-war"],
    sectors: ["creative-economy", "governance"],
  },
  {
    id: "lit-africabib-my-watch",
    title: "My watch",
    publisher: "AfricaBib (Prestige, Yaba, Lagos, 2014)",
    year: 2014,
    url: "https://m.africabib.org/rec.php?DB=a&RID=411307274",
    accessedAt: "2026-10-06",
    eras: ["military-rule", "democracy"],
    sectors: ["governance"],
  },
  {
    id: "lit-nln-journey-in-service",
    title: "A Journey in service: an autobiography",
    publisher: "National Library of Nigeria repository (Bookcraft, 2025)",
    year: 2025,
    url: "https://nigeriareposit.nln.gov.ng/items/be51c68b-c8cf-46da-a546-9bdd02a2e60b",
    accessedAt: "2026-10-06",
    eras: ["military-rule", "democracy"],
    sectors: ["governance"],
  },
  {
    id: "lit-brittlepaper-journey-in-service",
    title: "Former Nigerian Head of State Ibrahim Babangida Releases Long-Awaited Memoir, A Journey in Service",
    publisher: "Brittle Paper",
    year: 2025,
    url: "https://brittlepaper.com/2025/03/former-nigerian-head-of-state-ibrahim-babangida-releases-long-awaited-memoir-a-journey-in-service/",
    accessedAt: "2026-10-06",
    eras: ["military-rule"],
    sectors: ["governance"],
  },
  {
    id: "lit-guardian-gowon-memoir",
    title: "56 years later, Gowon relives civil war in autobiography",
    publisher: "The Guardian Nigeria",
    year: 2026,
    url: "https://guardian.ng/news/56-years-later-gowon-relives-civil-war-in-autobiography/",
    accessedAt: "2026-10-06",
    eras: ["civil-war", "military-rule"],
    sectors: ["governance"],
  },
  {
    id: "lit-naltf-gowon-memoir",
    title: "Former Head of State, Yakubu Gowon Launches Memoire, “My Life of Duty and Allegiance”",
    publisher: "Nigeria Alive Legacy Trust Fund (NALTF)",
    year: 2026,
    url: "https://naltf.gov.ng/former-head-of-state-yakubu-gowon-launches-memoire-my-life-of-duty-and-allegiance/",
    accessedAt: "2026-10-06",
    eras: ["civil-war", "military-rule"],
    sectors: ["governance"],
  },
  {
    id: "lit-guardian-abubakar-call-of-duty",
    title: "Unknown fact behind Abacha’s death: General Abdulsalami (rtd)",
    publisher: "The Guardian Nigeria",
    year: 2026,
    url: "https://guardian.ng/art/books/unknown-fact-behind-abachas-death-general-abdulsalami-rtd/",
    accessedAt: "2026-10-06",
    eras: ["military-rule", "democracy"],
    sectors: ["governance"],
  },
  {
    id: "lit-sunshine-about",
    title: "About Us",
    publisher: "Sunshine Bookseller",
    year: 2010,
    url: "https://sunshinebookseller.com/about-us/",
    accessedAt: "2026-10-06",
    eras: ["democracy"],
    sectors: ["creative-economy"],
  },
  {
    id: "lit-sunshine-memoirs",
    title: "MEMOIRS",
    publisher: "Sunshine Bookseller",
    year: 2026,
    url: "https://sunshinebookseller.com/product-category/memoirs/",
    accessedAt: "2026-10-06",
    eras: ["democracy"],
    sectors: ["creative-economy", "governance"],
  },
];

export const LITERATURE_WORKS: LiteratureWork[] = [
  {
    id: "palm-wine-drinkard",
    title: "The Palm-Wine Drinkard",
    medium: "book",
    year: 1952,
    creators: [{ name: "Amos Tutuola", role: "Author" }],
    periodId: "oral-to-print",
    settingLabel: "Yoruba quest lore rendered as modern prose",
    summary:
      "A drinkard follows his dead tapster into the town of the deads. Faber’s 1952 edition put Yoruba oral adventure into English print for a global audience.",
    verifiedClaim: "First published in London by Faber and Faber in 1952.",
    sourceIds: ["lit-faber-palm-wine-drinkard"],
    relatedTimelineIds: ["independence-1960"],
    coverMotif: "pre-colonial",
  },
  {
    id: "things-fall-apart",
    title: "Things Fall Apart",
    medium: "book",
    year: 1958,
    creators: [{ name: "Chinua Achebe", role: "Author", iconId: "chinua-achebe" }],
    periodId: "colonial-encounter",
    settingLabel: "Igbo village life meeting mission Christianity and colonial rule",
    summary:
      "Okonkwo’s Umuofia story became the most widely taught African novel in English and a fixed reference for how Nigerian fiction pictures the colonial break.",
    verifiedClaim: "Achebe’s debut novel, published by Heinemann in 1958.",
    sourceIds: ["lit-britannica-achebe"],
    relatedTimelineIds: ["independence-1960"],
    relatedIconIds: ["chinua-achebe"],
    coverMotif: "colonial",
  },
  {
    id: "death-and-the-kings-horseman",
    title: "Death and the King’s Horseman",
    medium: "play",
    year: 1975,
    creators: [{ name: "Wole Soyinka", role: "Playwright", iconId: "wole-soyinka" }],
    periodId: "colonial-encounter",
    settingLabel: "1940s Yoruba royal ritual under British colonial administration",
    summary:
      "Based on a 1940s incident, the play stages Elesin’s interrupted ritual suicide when colonial officers intervene. Published in 1975; world premiere in Nigeria in 1976.",
    verifiedClaim: "Published in 1975; BBC Culture records the 1976 Nigerian premiere.",
    sourceIds: ["lit-bbc-soyinka-horseman"],
    relatedTimelineIds: ["independence-1960"],
    relatedIconIds: ["wole-soyinka"],
    coverMotif: "colonial",
  },
  {
    id: "joys-of-motherhood",
    title: "The Joys of Motherhood",
    medium: "book",
    year: 1979,
    creators: [{ name: "Buchi Emecheta", role: "Author" }],
    periodId: "independence",
    settingLabel: "Igbo womanhood from village expectation to colonial Lagos",
    summary:
      "Nnu Ego’s life tracks fertility, migration, and the costs of motherhood as colonial Lagos remakes household economics.",
    verifiedClaim: "First published in London by Allison & Busby in 1979.",
    sourceIds: ["lit-caval-joys-motherhood"],
    relatedTimelineIds: ["independence-1960"],
    coverMotif: "independence",
  },
  {
    id: "famished-road",
    title: "The Famished Road",
    medium: "book",
    year: 1991,
    creators: [{ name: "Ben Okri", role: "Author", iconId: "ben-okri" }],
    periodId: "military-allegory",
    settingLabel: "An unnamed African city of the living and the spirit road",
    summary:
      "Azaro, an abiku spirit child, moves between marketplace politics and the spirit world. Jonathan Cape published the novel; it won the Booker Prize in 1991.",
    verifiedClaim: "Published by Jonathan Cape in 1991; winner of the 1991 Booker Prize.",
    sourceIds: ["lit-booker-famished-road"],
    relatedIconIds: ["ben-okri"],
    coverMotif: "military",
  },
  {
    id: "living-in-bondage",
    title: "Living in Bondage",
    medium: "film",
    year: 1992,
    creators: [
      { name: "Chris Obi Rapu", role: "Director" },
      { name: "Kenneth Nnebue", role: "Writer / producer credit" },
    ],
    periodId: "video-boom",
    settingLabel: "Early-1990s Lagos ambition, cult wealth, and VHS distribution",
    summary:
      "A straight-to-VHS Igbo-language drama about a businessman who joins a cult for wealth. Britannica treats it as the breakthrough title of the Nollywood VHS era.",
    verifiedClaim:
      "1992–1993 two-part film directed by Chris Obi Rapu; Britannica cites it as the VHS-era Nollywood breakthrough.",
    sourceIds: ["lit-britannica-living-in-bondage"],
    relatedTimelineIds: ["nollywood-birth"],
    coverMotif: "democracy",
  },
  {
    id: "saworoide",
    title: "Saworoide",
    medium: "film",
    year: 1999,
    creators: [{ name: "Tunde Kelani", role: "Director / producer", iconId: "tunde-kelani" }],
    periodId: "military-allegory",
    settingLabel: "Yoruba royal town allegory of corrupt rule and resistance",
    summary:
      "In Jogbo, a ruler who skips the saworoide coronation ritual faces the drum’s judgment. African Film Festival lists the 1999 Kelani political drama at 105 minutes.",
    verifiedClaim: "1999 Nigerian political drama directed by Tunde Kelani (AFF catalogue).",
    sourceIds: ["lit-aff-saworoide"],
    relatedTimelineIds: ["democracy-1999"],
    relatedIconIds: ["tunde-kelani"],
    coverMotif: "military",
  },
  {
    id: "purple-hibiscus",
    title: "Purple Hibiscus",
    medium: "book",
    year: 2003,
    creators: [{ name: "Chimamanda Ngozi Adichie", role: "Author", iconId: "chimamanda-adichie" }],
    periodId: "independence",
    settingLabel: "Post-independence Catholic household under private terror",
    summary:
      "Kambili grows up under a devout, violent father while Nigeria’s public crises press on the family. Algonquin published the debut novel in 2003.",
    verifiedClaim: "Debut novel published by Algonquin Books of Chapel Hill in 2003.",
    sourceIds: ["lit-algonquin-purple-hibiscus"],
    relatedIconIds: ["chimamanda-adichie"],
    coverMotif: "democracy",
  },
  {
    id: "half-of-a-yellow-sun",
    title: "Half of a Yellow Sun",
    medium: "book",
    year: 2006,
    creators: [{ name: "Chimamanda Ngozi Adichie", role: "Author", iconId: "chimamanda-adichie" }],
    periodId: "civil-war",
    settingLabel: "1960s Nigeria through the Biafran war",
    summary:
      "Ugwu, Olanna, Odenigbo, and Kainene live the slide from campus politics into the Civil War. Fourth Estate published the UK edition in 2006.",
    verifiedClaim: "First published in Great Britain in 2006 by Fourth Estate.",
    sourceIds: ["lit-fourth-estate-half-yellow-sun"],
    relatedTimelineIds: ["civil-war-1967"],
    relatedIconIds: ["chimamanda-adichie"],
    coverMotif: "conflict",
  },
  {
    id: "americanah",
    title: "Americanah",
    medium: "book",
    year: 2013,
    creators: [{ name: "Chimamanda Ngozi Adichie", role: "Author", iconId: "chimamanda-adichie" }],
    periodId: "contemporary",
    settingLabel: "Contemporary Nigeria, U.S. migration, and return",
    summary:
      "Ifemelu’s blog and return plot map hair, race, and class across Lagos and American cities. Knopf’s U.S. hardcover is dated 14 May 2013.",
    verifiedClaim: "Published 14 May 2013 by Alfred A. Knopf (U.S.); Fourth Estate issued the UK edition in 2013.",
    sourceIds: ["lit-knopf-americanah"],
    relatedIconIds: ["chimamanda-adichie"],
    coverMotif: "reform",
  },
  {
    id: "lionheart",
    title: "Lionheart",
    medium: "film",
    year: 2018,
    creators: [
      { name: "Genevieve Nnaji", role: "Director / lead" },
      { name: "Pete Edochie", role: "Cast", iconId: "pete-edochie" },
      { name: "Onyeka Onwenu", role: "Cast", iconId: "onyeka-onwenu" },
    ],
    periodId: "contemporary",
    settingLabel: "Contemporary Igbo family transport business under succession stress",
    summary:
      "Adaeze fights to keep Lionheart Transport alive when her father falls ill. Variety reported Netflix’s worldwide rights deal as the streamer’s first Nigerian original film, ahead of the 2018 Toronto premiere.",
    verifiedClaim:
      "2018 Nigerian film directed by Genevieve Nnaji; Variety reported Netflix’s first Nigerian original film acquisition at TIFF.",
    sourceIds: ["lit-variety-lionheart"],
    relatedTimelineIds: ["nollywood-birth"],
    relatedIconIds: ["pete-edochie", "onyeka-onwenu"],
    coverMotif: "reform",
  },
  {
    id: "king-of-boys",
    title: "King of Boys",
    medium: "film",
    year: 2018,
    creators: [{ name: "Kemi Adetiba", role: "Writer / director" }],
    periodId: "contemporary",
    settingLabel: "Contemporary Lagos underworld and political ambition",
    summary:
      "Alhaja Eniola Salami’s grip on Lagos power meets a succession crisis. The Guardian Nigeria reported a 26 October 2018 cinema release for Adetiba’s film.",
    verifiedClaim: "Directed by Kemi Adetiba; Nigerian cinema release reported for 26 October 2018.",
    sourceIds: ["lit-guardian-king-of-boys"],
    coverMotif: "democracy",
  },
  {
    id: "anikulapo",
    title: "Aníkúlápó",
    medium: "film",
    year: 2022,
    creators: [{ name: "Kunle Afolayan", role: "Director / producer" }],
    periodId: "contemporary",
    settingLabel: "Yoruba-language epic set in a precolonial royal world",
    summary:
      "After an affair with a queen, a traveler meets a bird said to give and take life. Netflix lists the 2022 title; BBFC records Afolayan as director and a 30 September 2022 release.",
    verifiedClaim: "2022 Netflix film directed by Kunle Afolayan (Netflix title page; BBFC record).",
    sourceIds: ["lit-netflix-anikulapo", "lit-bbfc-anikulapo"],
    coverMotif: "pre-colonial",
  },
  {
    id: "path-to-nigerian-freedom",
    title: "Path to Nigerian Freedom",
    medium: "book",
    year: 1947,
    creators: [{ name: "Obafemi Awolowo", role: "Author", iconId: "obafemi-awolowo" }],
    periodId: "leaders-memory",
    settingLabel: "Late-colonial case for federal self-government",
    summary:
      "Awolowo’s early political book argued for federation to protect regional nationalities inside a free Nigeria. Britannica and AfricaBib place the Faber and Faber London edition in 1947.",
    verifiedClaim: "Published in London by Faber and Faber in 1947 (AfricaBib; Britannica).",
    sourceIds: ["lit-britannica-path-nigerian-freedom", "lit-africabib-path-nigerian-freedom"],
    relatedTimelineIds: ["independence-1960"],
    relatedIconIds: ["obafemi-awolowo"],
    coverMotif: "colonial",
  },
  {
    id: "awo-autobiography",
    title: "Awo: The Autobiography of Chief Obafemi Awolowo",
    medium: "memoir",
    year: 1960,
    creators: [{ name: "Obafemi Awolowo", role: "Author", iconId: "obafemi-awolowo" }],
    periodId: "leaders-memory",
    settingLabel: "Western Region politics on the eve of independence",
    summary:
      "Completed in the independence year, the autobiography covers Awolowo’s youth, education, and Action Group politics. Cambridge University Press issued the 1960 edition (Internet Archive; AbeBooks first-edition listings).",
    verifiedClaim: "Published by Cambridge University Press in 1960.",
    sourceIds: ["lit-archive-awo", "lit-abebooks-awo", "lit-sunshine-memoirs"],
    relatedTimelineIds: ["independence-1960"],
    relatedIconIds: ["obafemi-awolowo"],
    coverMotif: "independence",
  },
  {
    id: "my-command",
    title: "My Command",
    medium: "memoir",
    year: 1980,
    creators: [{ name: "Olusegun Obasanjo", role: "Author", iconId: "olusegun-obasanjo" }],
    periodId: "leaders-memory",
    settingLabel: "Nigerian Civil War from a federal field commander’s desk",
    summary:
      "Obasanjo’s personal narrative of the 1967–1970 war. The National Library of Australia catalogue records the Heinemann 1980 edition (Ibadan/London).",
    verifiedClaim: "Published by Heinemann in 1980 as an account of the Nigerian Civil War, 1967–1970.",
    sourceIds: ["lit-nla-my-command"],
    relatedTimelineIds: ["civil-war-1967"],
    relatedIconIds: ["olusegun-obasanjo"],
    coverMotif: "conflict",
  },
  {
    id: "why-we-struck",
    title: "Why We Struck",
    medium: "memoir",
    year: 1981,
    creators: [{ name: "Adewale Ademoyega", role: "Author" }],
    periodId: "leaders-memory",
    settingLabel: "January 1966 coup from a participant’s account",
    summary:
      "Ademoyega’s memoir of the first Nigerian coup. The National Library of Australia catalogue records Evans Brothers (Nigeria Publishers), Ibadan, 1981.",
    verifiedClaim: "Published in Ibadan by Evans Brothers in 1981.",
    sourceIds: ["lit-nla-why-we-struck", "lit-sunshine-memoirs"],
    relatedTimelineIds: ["1966-coups"],
    coverMotif: "military",
  },
  {
    id: "there-was-a-country",
    title: "There Was a Country",
    medium: "memoir",
    year: 2012,
    creators: [{ name: "Chinua Achebe", role: "Author", iconId: "chinua-achebe" }],
    periodId: "leaders-memory",
    settingLabel: "Biafra and the Civil War from a writer’s vantage",
    summary:
      "Achebe’s personal history of Biafra mixes memoir, history, and poetry. Penguin’s UK edition is dated 2012.",
    verifiedClaim: "Published by Penguin in 2012 as a personal history of Biafra.",
    sourceIds: ["lit-penguin-there-was-a-country"],
    relatedTimelineIds: ["civil-war-1967"],
    relatedIconIds: ["chinua-achebe"],
    coverMotif: "conflict",
  },
  {
    id: "my-watch",
    title: "My Watch",
    medium: "memoir",
    year: 2014,
    creators: [{ name: "Olusegun Obasanjo", role: "Author", iconId: "olusegun-obasanjo" }],
    periodId: "leaders-memory",
    settingLabel: "Military years and the 1999–2007 civilian presidency",
    summary:
      "Multi-volume autobiography covering Obasanjo’s military and civilian watches. AfricaBib records the 2014 Prestige (Yaba, Lagos) edition.",
    verifiedClaim: "Published in Yaba, Lagos by Prestige in 2014 (AfricaBib).",
    sourceIds: ["lit-africabib-my-watch"],
    relatedTimelineIds: ["democracy-1999"],
    relatedIconIds: ["olusegun-obasanjo"],
    coverMotif: "democracy",
  },
  {
    id: "journey-in-service",
    title: "A Journey in Service",
    medium: "memoir",
    year: 2025,
    creators: [{ name: "Ibrahim Badamasi Babangida", role: "Author" }],
    periodId: "leaders-memory",
    settingLabel: "1985–1993 military presidency, reforms, and June 12",
    summary:
      "Babangida’s autobiography of childhood, army years, and the military presidency. The National Library of Nigeria lists Bookcraft (Ibadan) as publisher for 2025; Brittle Paper reported the February 2025 release.",
    verifiedClaim: "Published in 2025 by Bookcraft Africa, Ibadan (NLN repository; Brittle Paper).",
    sourceIds: [
      "lit-nln-journey-in-service",
      "lit-brittlepaper-journey-in-service",
      "lit-sunshine-memoirs",
    ],
    relatedTimelineIds: ["military-decades", "democracy-1999"],
    coverMotif: "military",
  },
  {
    id: "my-life-of-duty-and-allegiance",
    title: "My Life of Duty and Allegiance",
    medium: "memoir",
    year: 2026,
    creators: [{ name: "Yakubu Gowon", role: "Author", iconId: "yakubu-gowon" }],
    periodId: "leaders-memory",
    settingLabel: "1966–1975 headship and the Civil War years",
    summary:
      "Gowon’s long-awaited autobiography. The Guardian Nigeria and NALTF report an 881-page Havilah Group volume launched in Abuja on 19 May 2026.",
    verifiedClaim: "Published by Havilah Group; launched in Abuja on 19 May 2026 (Guardian Nigeria; NALTF).",
    sourceIds: [
      "lit-guardian-gowon-memoir",
      "lit-naltf-gowon-memoir",
      "lit-sunshine-memoirs",
    ],
    relatedTimelineIds: ["civil-war-1967"],
    relatedIconIds: ["yakubu-gowon"],
    coverMotif: "conflict",
  },
  {
    id: "call-of-duty-abubakar",
    title: "Call of Duty",
    medium: "memoir",
    year: 2026,
    creators: [{ name: "Abdulsalami Abubakar", role: "Author" }],
    periodId: "leaders-memory",
    settingLabel: "1998–1999 transition from Abacha to the Fourth Republic",
    summary:
      "Abubakar’s account of the short headship that midwifed the 1999 constitution and handover. The Guardian Nigeria reports Cable Books (Cable Media & Publishing) as publisher, with nationwide retail including Sunshine Bookseller.",
    verifiedClaim: "Published by Cable Books in 2026 (Guardian Nigeria).",
    sourceIds: ["lit-guardian-abubakar-call-of-duty", "lit-sunshine-memoirs"],
    relatedTimelineIds: ["democracy-1999"],
    coverMotif: "democracy",
  },
];

export function getLiteratureWorksByPeriod(periodId: LiteraturePeriodId): LiteratureWork[] {
  return LITERATURE_WORKS.filter((work) => work.periodId === periodId);
}

export function getLiteratureSourceIds(): string[] {
  return LITERATURE_SOURCES.map((source) => source.id);
}

export function getLiteratureHeroRail() {
  const sorted = [...LITERATURE_WORKS].sort((a, b) => a.year - b.year);
  const earliest = sorted[0];
  const memoirCount = LITERATURE_WORKS.filter(
    (work) => work.medium === "memoir" || work.medium === "biography",
  ).length;
  const fictionCount = LITERATURE_WORKS.filter(
    (work) => work.medium === "book" || work.medium === "play",
  ).length;
  const screenCount = LITERATURE_WORKS.filter(
    (work) => work.medium === "film" || work.medium === "series",
  ).length;

  return [
    {
      year: String(earliest?.year ?? LITERATURE_PAGE_META.railFallbackYear),
      label: LITERATURE_PAGE_META.railEarliestLabel,
      href: `#${earliest?.id ?? LITERATURE_PAGE_META.railFallbackEarliestId}`,
    },
    {
      year: `${memoirCount}`,
      label: LITERATURE_PAGE_META.railMemoirsLabel,
      href: LITERATURE_PAGE_META.railMemoirsHref,
    },
    {
      year: `${fictionCount}`,
      label: LITERATURE_PAGE_META.railBooksLabel,
      href: LITERATURE_PAGE_META.railBooksHref,
    },
    {
      year: `${screenCount}`,
      label: LITERATURE_PAGE_META.railFilmsLabel,
      href: LITERATURE_PAGE_META.railFilmsHref,
      accent: true as const,
    },
  ];
}
