import type { SectorKeyDriver } from "@/types/content";

/**
 * Key drivers per sector. Values reuse figures already published on each sector page
 * and must cite an id from that sector's sourceIds (or shared Tier-1 catalogue).
 */
export const SECTOR_KEY_DRIVERS: Record<string, SectorKeyDriver[]> = {
  economy: [
    {
      id: "gdp-per-capita",
      icon: "chart",
      label: "GDP per capita",
      why: "The income path that converts growth into living standards through 2050.",
      baseline: "$2,162",
      sourceId: "world-bank-gdp-current-usd",
    },
    {
      id: "manufacturing-share",
      icon: "factory",
      label: "Manufacturing share of GDP",
      why: "Tracks whether industry deepens beyond extractives and import dependence.",
      baseline: "8.9%",
      sourceId: "unido-manufacturing",
    },
    {
      id: "oil-export-share",
      icon: "oil",
      label: "Oil share of exports",
      why: "Fiscal and FX exposure to oil prices until non-oil trade scales.",
      baseline: "85%",
      sourceId: "world-bank-nigeria-overview",
    },
    {
      id: "informal-employment",
      icon: "briefcase",
      label: "Informal employment share",
      why: "Shows how much of the labour force sits outside formal tax and social systems.",
      baseline: "~93%",
      sourceId: "nbs-nlfs-2024",
    },
  ],
  technology: [
    {
      id: "mobile-internet",
      icon: "wifi",
      label: "Regular mobile internet use",
      why: "The connectivity floor for digital public services, commerce, and skills.",
      baseline: "29%",
      sourceId: "gsma-nigeria-digital",
    },
    {
      id: "internet-users",
      icon: "world-www",
      label: "Individuals using the internet",
      why: "Broader access measure that includes fixed and shared connections.",
      baseline: "55%",
      sourceId: "itu-digital-indicators",
    },
    {
      id: "startup-funding",
      icon: "rocket",
      label: "Startup funding (2024)",
      why: "Capital formation in software and platforms that can compound to 2050.",
      baseline: "$1.2B",
      sourceId: "mckinsey-nigeria-2050",
    },
    {
      id: "fintech-users",
      icon: "device-mobile",
      label: "Fintech users",
      why: "Digital payments as the first large-scale non-oil tech adoption path.",
      baseline: "70M+",
      sourceId: "gsma-nigeria-digital",
    },
  ],
  governance: [
    {
      id: "corruption-rank",
      icon: "scale",
      label: "Corruption Perceptions rank",
      why: "Investor and citizen trust in rules that long-horizon plans need.",
      baseline: "145/180",
      sourceId: "transparency-corruption-index",
    },
    {
      id: "voter-turnout",
      icon: "vote",
      label: "Voter turnout (2023)",
      why: "Electoral participation that legitimises successive reform mandates.",
      baseline: "27%",
      sourceId: "idea-election-turnout",
    },
    {
      id: "egov-index",
      icon: "building-bank",
      label: "E-government readiness",
      why: "Digital state capacity for service delivery and transparency.",
      baseline: "Low-middle",
      sourceId: "heritage-economic-freedom",
    },
    {
      id: "civil-service-digital",
      icon: "device-desktop",
      label: "Civil service digitalization",
      why: "How far routine government work has moved off paper processes.",
      baseline: "~35%",
      sourceId: "agenda-2050-npc",
    },
  ],
  education: [
    {
      id: "literacy",
      icon: "book",
      label: "Adult literacy rate",
      why: "Foundational skill stock for a larger, more productive workforce.",
      baseline: "70.4%",
      sourceId: "unesco-literacy-nigeria",
    },
    {
      id: "out-of-school",
      icon: "school",
      label: "Out-of-school children",
      why: "The pipeline gap that 2050 human capital scenarios have to close.",
      baseline: "20M",
      sourceId: "unesco-education-spending",
    },
    {
      id: "tertiary",
      icon: "users",
      label: "Tertiary enrollment rate",
      why: "Advanced skills for industry, health, and public administration.",
      baseline: "10.2%",
      sourceId: "unesco-tertiary-enrollment",
    },
    {
      id: "doctors",
      icon: "stethoscope",
      label: "Doctors per 1,000 people",
      why: "Health workforce density that education and training systems must feed.",
      baseline: "0.4",
      sourceId: "who-health-workforce",
    },
  ],
  energy: [
    {
      id: "installed-capacity",
      icon: "bolt",
      label: "Installed power capacity",
      why: "Nameplate generation the grid can call on as demand rises.",
      baseline: "13.6 GW",
      sourceId: "nerc-quarterly",
    },
    {
      id: "available-capacity",
      icon: "plug",
      label: "Available capacity",
      why: "What actually reaches the system after outages and constraints.",
      baseline: "~5.4 GW",
      sourceId: "nerc-quarterly",
    },
    {
      id: "grid-access",
      icon: "home-bolt",
      label: "Grid access",
      why: "Household and firm connection to reliable electricity service.",
      baseline: "62%",
      sourceId: "world-bank-electricity-access",
    },
    {
      id: "renewable-share",
      icon: "sun",
      label: "Renewable energy share",
      why: "Clean capacity share on the Energy Transition Plan path to 2050.",
      baseline: "18%",
      sourceId: "iea-nigeria-energy",
    },
  ],
  security: [
    {
      id: "police-density",
      icon: "shield",
      label: "Police per 100,000 people",
      why: "Frontline public-safety capacity relative to population growth.",
      baseline: "187",
      sourceId: "unodc-crime-stats",
    },
    {
      id: "prison-population",
      icon: "building",
      label: "Prison population",
      why: "Custody load that justice reform and case clearance must manage.",
      baseline: "73,000+",
      sourceId: "unodc-crime-stats",
    },
    {
      id: "conflict-fatalities",
      icon: "alert",
      label: "Conflict fatalities (2024)",
      why: "Violence intensity that blocks investment and internal mobility.",
      baseline: "High",
      sourceId: "ucdp-conflict-data",
    },
    {
      id: "case-backlog",
      icon: "gavel",
      label: "Justice case backlog",
      why: "Court delay that weakens deterrence and contract enforcement.",
      baseline: "Millions",
      sourceId: "world-bank-nigeria-overview",
    },
  ],
  healthcare: [
    {
      id: "life-expectancy",
      icon: "heartbeat",
      label: "Life expectancy",
      why: "Composite outcome of primary care, nutrition, and disease control.",
      baseline: "55 years",
      sourceId: "who-nigeria-health",
    },
    {
      id: "health-spending",
      icon: "coin",
      label: "Health spending (% of GDP)",
      why: "Public and private resource intensity behind 2050 coverage goals.",
      baseline: "3.2%",
      sourceId: "who-nigeria-health",
    },
    {
      id: "physicians",
      icon: "stethoscope",
      label: "Physicians per 10,000",
      why: "Clinical workforce density against a rising population.",
      baseline: "3.8",
      sourceId: "who-health-workforce",
    },
    {
      id: "maternal-mortality",
      icon: "baby-carriage",
      label: "Maternal mortality",
      why: "A hard test of referral systems and basic emergency obstetric care.",
      baseline: "1,047 / 100k",
      sourceId: "who-nigeria-health",
    },
  ],
  agriculture: [
    {
      id: "ag-gdp",
      icon: "plant",
      label: "Agriculture share of GDP",
      why: "How large the farm economy remains as industry and services grow.",
      baseline: "24%",
      sourceId: "fao-nigeria-agriculture",
    },
    {
      id: "smallholder",
      icon: "users",
      label: "Smallholder share of farms",
      why: "Production structure that extension, finance, and markets must reach.",
      baseline: "80%",
      sourceId: "fao-nigeria-agriculture",
    },
    {
      id: "post-harvest-loss",
      icon: "truck",
      label: "Post-harvest loss",
      why: "Food already grown that never reaches consumers or processors.",
      baseline: "40%",
      sourceId: "fao-nigeria-agriculture",
    },
    {
      id: "irrigation",
      icon: "droplet",
      label: "Irrigated land share",
      why: "Climate resilience of yields as rainfall variability rises.",
      baseline: "1.8%",
      sourceId: "afdb-agriculture",
    },
  ],
  "creative-economy": [
    {
      id: "nollywood-output",
      icon: "movie",
      label: "Nollywood film output",
      why: "Volume of screen production that can scale exports and jobs.",
      baseline: "2,500+ films/year",
      sourceId: "nollywood-industry-report",
    },
    {
      id: "music-export",
      icon: "music",
      label: "Music export revenue",
      why: "Afrobeats and recorded music as a hard-currency creative earner.",
      baseline: "$500M+",
      sourceId: "unesco-creative-economy",
    },
    {
      id: "creative-gdp",
      icon: "palette",
      label: "Creative share of GDP",
      why: "Measured weight of culture industries in national output.",
      baseline: "1.8%",
      sourceId: "unesco-creative-economy",
    },
    {
      id: "creative-jobs",
      icon: "briefcase",
      label: "Creative jobs",
      why: "Employment in film, music, design, and related services.",
      baseline: "4M+",
      sourceId: "unesco-creative-economy",
    },
  ],
  manufacturing: [
    {
      id: "mfg-gdp",
      icon: "factory",
      label: "Manufacturing share of GDP",
      why: "Industrial depth relative to the 2050 diversification case.",
      baseline: "9%",
      sourceId: "unido-manufacturing",
    },
    {
      id: "industrial-jobs",
      icon: "briefcase",
      label: "Industrial jobs",
      why: "Formal factory and industrial employment scale.",
      baseline: "5M",
      sourceId: "afdb-industrialization",
    },
    {
      id: "capacity-utilization",
      icon: "bolt",
      label: "Capacity utilization",
      why: "How much existing plant runs when power and demand allow.",
      baseline: "~55%",
      sourceId: "nerc-quarterly",
    },
    {
      id: "mfg-exports",
      icon: "truck",
      label: "Manufacturing export value",
      why: "Non-oil goods that can stabilize FX earnings.",
      baseline: "$8B",
      sourceId: "unido-manufacturing",
    },
  ],
  "financial-inclusion": [
    {
      id: "banked-adults",
      icon: "building-bank",
      label: "Banked adult share",
      why: "Formal account ownership as the base for savings and credit.",
      baseline: "56%",
      sourceId: "world-bank-financial-inclusion",
    },
    {
      id: "mobile-money",
      icon: "device-mobile",
      label: "Mobile money users",
      why: "Reach of digital wallets beyond traditional branch banking.",
      baseline: "85M",
      sourceId: "cbn-financial-access",
    },
    {
      id: "private-credit",
      icon: "coin",
      label: "Credit to private sector",
      why: "Depth of bank lending relative to the size of the economy.",
      baseline: "12% of GDP",
      sourceId: "world-bank-financial-inclusion",
    },
    {
      id: "agent-banking",
      icon: "building-store",
      label: "Agent banking outlets",
      why: "Last-mile cash-in/cash-out points for under-served communities.",
      baseline: "1.2M",
      sourceId: "cbn-financial-access",
    },
  ],
  transportation: [
    {
      id: "lpi",
      icon: "truck",
      label: "Logistics Performance Index",
      why: "Trade friction in customs, freight, and corridor reliability.",
      baseline: "2.6 / 5",
      sourceId: "world-bank-lpi",
    },
    {
      id: "road-deaths",
      icon: "road",
      label: "Road deaths per 100,000",
      why: "Safety cost of the road network households and freight rely on.",
      baseline: "17.2",
      sourceId: "who-road-safety",
    },
    {
      id: "air-passengers",
      icon: "plane",
      label: "Air passengers per 1,000",
      why: "Aviation intensity for domestic connectivity and tourism.",
      baseline: "31",
      sourceId: "world-bank-nigeria-overview",
    },
    {
      id: "rail-lines",
      icon: "train",
      label: "Standard-gauge passenger lines",
      why: "Modern rail corridors in service for people and freight.",
      baseline: "2 in service",
      sourceId: "afdb-industrialization",
    },
  ],
  "real-estate": [
    {
      id: "urban-share",
      icon: "building",
      label: "Urban population share",
      why: "Pace of city growth that housing and land systems must absorb.",
      baseline: "62%",
      sourceId: "un-world-urbanization-prospects",
    },
    {
      id: "slum-share",
      icon: "home",
      label: "Urban population in slums",
      why: "Share of city residents in inadequate housing.",
      baseline: "48.5%",
      sourceId: "world-bank-g7-indicators",
    },
    {
      id: "housing-deficit",
      icon: "map-pin",
      label: "Housing deficit range",
      why: "Unit gap that formal supply and finance have to close.",
      baseline: "22–28 million units",
      sourceId: "cahf-nigeria-housing",
    },
    {
      id: "mortgages",
      icon: "coin",
      label: "Mortgages to GDP",
      why: "Depth of long-term housing finance relative to the economy.",
      baseline: "0.6%",
      sourceId: "cahf-nigeria-housing",
    },
  ],
  tourism: [
    {
      id: "visitors",
      icon: "plane",
      label: "International visitors (2023)",
      why: "Recent inbound travel volume after pandemic disruption.",
      baseline: "1.2 million",
      sourceId: "ntdc-akwaaba-2024",
    },
    {
      id: "arrivals-peak",
      icon: "users",
      label: "Arrivals (2016 peak)",
      why: "Pre-disruption peak that recovery scenarios can reference.",
      baseline: "5.3 million",
      sourceId: "world-bank-tourism",
    },
    {
      id: "receipts",
      icon: "coin",
      label: "Tourism receipts (2019)",
      why: "Foreign-exchange earnings from travel before COVID shock years.",
      baseline: "$1.47 billion",
      sourceId: "world-bank-tourism",
    },
    {
      id: "heritage-sites",
      icon: "photo",
      label: "UNESCO World Heritage sites",
      why: "Flagship cultural assets that anchor longer-stay tourism.",
      baseline: "2",
      sourceId: "unesco-world-heritage",
    },
  ],
};
