import type { Source } from "@/types/content";
import { PHASE2_RAW_SOURCES, PHASE2_SOURCE_META } from "./phase2/sources";
import { ICON_SOURCES } from "./icons";

const RAW_SOURCES: Source[] = [
  {
    id: "world-bank-nigeria-overview",
    title: "Nigeria Economic Overview",
    publisher: "World Bank",
    year: 2024,
    url: "https://www.worldbank.org/en/country/nigeria/overview",
  },
  {
    id: "nbs-gdp-report-2024",
    title: "Nigerian Gross Domestic Product Report Q4 2024",
    publisher: "National Bureau of Statistics (NBS)",
    year: 2025,
    url: "https://www.nigerianstat.gov.ng",
  },
  {
    id: "mckinsey-nigeria-2050",
    title: "Nigeria's Path to Prosperity: Agenda 2050 Scenarios",
    publisher: "McKinsey Global Institute",
    year: 2023,
    url: "https://www.mckinsey.com/mgi",
  },
  {
    id: "pwc-nigeria-2050",
    title: "The Long View: How Will the Global Economic Order Change by 2050?",
    publisher: "PwC",
    year: 2017,
    url: "https://www.pwc.com.au/government/pwc-the-world-in-2050-full-report-feb-2017.pdf",
  },
  {
    id: "undp-hdi-nigeria",
    title: "Human Development Report. Nigeria",
    publisher: "UNDP",
    year: 2024,
    url: "https://hdr.undp.org",
  },
  {
    id: "unesco-literacy-nigeria",
    title: "Adult Literacy Rate. Nigeria (SE.ADT.LITR.ZS)",
    publisher: "UNESCO Institute for Statistics",
    year: 2024,
    url: "https://databrowser.uis.unesco.org/",
    accessedAt: "2026-10-04",
  },
  {
    id: "unesco-tertiary-enrollment",
    title: "School Enrollment, Tertiary (% Gross). Nigeria (SE.TER.ENRR)",
    publisher: "UNESCO Institute for Statistics",
    year: 2011,
    url: "https://data.worldbank.org/indicator/SE.TER.ENRR?locations=NG",
    accessedAt: "2026-10-04",
  },
  {
    id: "iea-nigeria-energy",
    title: "Nigeria Energy Outlook / World Energy Outlook",
    publisher: "International Energy Agency",
    year: 2024,
    url: "https://www.iea.org/articles/nigeria-energy-outlook",
  },
  {
    id: "gsma-nigeria-digital",
    title: "The Role of Mobile Technology in Driving the Digital Economy in Nigeria",
    publisher: "GSMA",
    year: 2024,
    url: "https://www.gsma.com/about-us/regions/sub-saharan-africa/wp-content/uploads/2024/05/NigeriaDigitalEconomy_R3_Web.pdf",
    accessedAt: "2026-10-04",
  },
  {
    id: "transparency-corruption-index",
    title: "Corruption Perceptions Index",
    publisher: "Transparency International",
    year: 2024,
    url: "https://www.transparency.org",
  },
  {
    id: "world-bank-doing-business",
    title: "Ease of Doing Business. Historical Data",
    publisher: "World Bank",
    year: 2020,
    url: "https://archive.doingbusiness.org",
  },
  {
    id: "sipri-security-africa",
    title: "Armed Conflict Survey. West Africa",
    publisher: "SIPRI",
    year: 2024,
    url: "https://www.sipri.org",
  },
  {
    id: "npc-population-projection",
    title: "Population Projection for Nigeria 2023–2050",
    publisher: "National Population Commission",
    year: 2023,
    url: "https://nationalpopulation.gov.ng",
  },
  {
    id: "afdb-industrialization",
    title: "Industrialization Strategy for Africa. Nigeria Case Study",
    publisher: "African Development Bank",
    year: 2023,
    url: "https://www.afdb.org",
  },
  {
    id: "heritage-economic-freedom",
    title: "Index of Economic Freedom. Nigeria",
    publisher: "Heritage Foundation",
    year: 2024,
    url: "https://www.heritage.org",
  },
  {
    id: "cbo-nigeria-history",
    title: "Colonial and Post-Colonial Nigeria: A Historical Overview",
    publisher: "Cambridge University Press (academic reference)",
    year: 2022,
  },
  {
    id: "agenda-2050-npc",
    title: "Nigeria Agenda 2050",
    publisher: "Federal Ministry of Budget and Economic Planning",
    year: 2023,
    url: "https://faolex.fao.org/docs/pdf/nig217433.pdf",
    accessedAt: "2026-10-04",
  },
  {
    id: "un-wpp-2024",
    title: "World Population Prospects 2024. Nigeria",
    publisher: "United Nations Population Division",
    year: 2024,
    url: "https://population.un.org/wpp/",
    accessedAt: "2026-10-04",
  },
  {
    id: "nerc-quarterly",
    title: "Nigerian Electricity Regulatory Commission Quarterly Reports",
    publisher: "Nigerian Electricity Regulatory Commission",
    year: 2025,
    url: "https://nerc.gov.ng/",
    accessedAt: "2026-10-04",
  },
  {
    id: "nigeria-etp",
    title: "Nigeria Energy Transition Plan (Power sector pathway)",
    publisher: "Energy Transition Office / SEforALL",
    year: 2025,
    url: "https://www.energytransition.gov.ng/power/",
    accessedAt: "2026-10-04",
  },
  {
    id: "nbs-nlfs-2024",
    title: "Nigeria Labour Force Survey (NLFS)",
    publisher: "National Bureau of Statistics (NBS)",
    year: 2024,
    url: "https://www.nigerianstat.gov.ng/pdfuploads/NLFS_Q1_2024_Report.pdf",
    accessedAt: "2026-10-04",
  },
  {
    id: "world-bank-ndu-2025",
    title: "Nigeria Development Update. Building Momentum for Inclusive Growth",
    publisher: "World Bank",
    year: 2025,
    url: "https://thedocs.worldbank.org/en/doc/18bb17d3b2d203e19fc8ecf281ed21da-0360012025/nigeria-development-update-building-momentum-for-inclusive-growth",
    accessedAt: "2026-10-04",
  },
  {
    id: "un-world-urbanization-prospects",
    title: "World Urbanization Prospects / World Cities Report statistical annex",
    publisher: "UN DESA / UN-Habitat",
    year: 2022,
    url: "https://unhabitat.org/sites/default/files/2022/07/statistical_annex_wcr_2022.pdf",
    accessedAt: "2026-10-04",
  },
  {
    id: "irena-nigeria-energy",
    title: "IRENA Energy Profile. Nigeria",
    publisher: "International Renewable Energy Agency",
    year: 2024,
    url: "https://www.irena.org/",
    accessedAt: "2026-10-04",
  },
  {
    id: "world-bank-electricity-access",
    title: "Access to Electricity (% of Population). Nigeria",
    publisher: "World Bank Data",
    year: 2025,
    url: "https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS?locations=NG",
    accessedAt: "2026-10-04",
  },
  {
    id: "world-bank-g7-indicators",
    title: "World Development Indicators. G7 Economies",
    publisher: "World Bank",
    year: 2024,
    url: "https://data.worldbank.org",
  },
  {
    id: "ilo-employment-stats",
    title: "ILOSTAT Informal Employment and Labour Statistics",
    publisher: "International Labour Organization",
    year: 2024,
    url: "https://ilostat.ilo.org/data/snapshots/informal-employment-rate/",
  },
  {
    id: "itu-digital-indicators",
    title: "ICT Development Index & Digital Indicators",
    publisher: "International Telecommunication Union",
    year: 2024,
    url: "https://www.itu.int",
  },
  {
    id: "wipo-ip-stats",
    title: "World Intellectual Property Indicators",
    publisher: "WIPO",
    year: 2024,
    url: "https://www.wipo.int",
  },
  {
    id: "idea-election-turnout",
    title: "Voter Turnout Database",
    publisher: "International IDEA",
    year: 2024,
    url: "https://www.idea.int",
  },
  {
    id: "international-budget-partnership",
    title: "Open Budget Survey",
    publisher: "International Budget Partnership",
    year: 2023,
    url: "https://internationalbudget.org",
  },
  {
    id: "statehouse-2026-appropriation",
    title: "President Tinubu Assents to 2026 Appropriation Bill and 2025 Budget Extension",
    publisher: "The State House, Abuja",
    year: 2026,
    url: "https://statehouse.gov.ng/president-tinubu-assents-to-2026-appropriation-bill-and-2025-budget-extension/",
  },
  {
    id: "unesco-education-spending",
    title: "Education Finance Watch",
    publisher: "UNESCO",
    year: 2024,
    url: "https://www.unesco.org",
  },
  {
    id: "who-health-workforce",
    title: "Global Health Workforce Statistics",
    publisher: "World Health Organization",
    year: 2024,
    url: "https://www.who.int",
  },
  {
    id: "global-peace-index",
    title: "Global Peace Index",
    publisher: "Institute for Economics & Peace",
    year: 2024,
    url: "https://www.visionofhumanity.org",
  },
  {
    id: "unodc-crime-stats",
    title: "UNODC Crime & Criminal Justice Statistics",
    publisher: "United Nations Office on Drugs and Crime",
    year: 2023,
    url: "https://www.unodc.org",
  },
  {
    id: "ucdp-conflict-data",
    title: "UCDP Battle-Related Deaths Dataset",
    publisher: "Uppsala Conflict Data Program",
    year: 2024,
    url: "https://ucdp.uu.se",
  },
  {
    id: "nigeria-constitution-1999",
    title: "Constitution of the Federal Republic of Nigeria 1999 (as amended)",
    publisher: "Federal Republic of Nigeria",
    year: 1999,
    url: "https://placng.org/lawsofnigeria/laws/C23.pdf",
  },
  {
    id: "world-bank-population-total",
    title: "Population, total - Nigeria",
    publisher: "World Bank Data",
    year: 2025,
    url: "https://data.worldbank.org/indicator/SP.POP.TOTL?locations=NG",
  },
  {
    id: "world-bank-gdp-current-usd",
    title: "GDP (current US$) - Nigeria",
    publisher: "World Bank Data",
    year: 2025,
    url: "https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?locations=NG",
  },
  {
    id: "state-house-president-profile",
    title: "President Bola Ahmed Tinubu",
    publisher: "State House, Abuja",
    year: 2026,
    url: "https://statehouse.gov.ng/president-bola-ahmed-tinubu/",
  },
  {
    id: "state-house-vice-president-profile",
    title: "Vice President Kashim Shettima",
    publisher: "State House, Abuja",
    year: 2026,
    url: "https://statehouse.gov.ng/vice-president-kashim-shettima/",
  },
  ...PHASE2_RAW_SOURCES,
];

const SOURCE_META: Record<string, Pick<Source, "sectors" | "eras">> = {
  "world-bank-nigeria-overview": { sectors: ["economy", "governance", "energy", "security", "transportation", "real-estate", "tourism"] },
  "nbs-gdp-report-2024": { sectors: ["economy"] },
  "mckinsey-nigeria-2050": { sectors: ["economy", "technology", "education"] },
  "pwc-nigeria-2050": { sectors: ["economy"] },
  "undp-hdi-nigeria": { sectors: ["education", "security"] },
  "unesco-literacy-nigeria": { sectors: ["education"] },
  "unesco-tertiary-enrollment": { sectors: ["education"] },
  "iea-nigeria-energy": { sectors: ["energy"] },
  "gsma-nigeria-digital": { sectors: ["technology", "tourism"] },
  "transparency-corruption-index": { sectors: ["governance"] },
  "world-bank-doing-business": { sectors: ["economy", "governance", "real-estate"] },
  "sipri-security-africa": { sectors: ["security"], eras: ["civil-war", "military-rule"] },
  "npc-population-projection": { sectors: ["economy", "education", "real-estate"] },
  "afdb-industrialization": { sectors: ["economy", "energy", "transportation", "manufacturing"] },
  "heritage-economic-freedom": { sectors: ["governance", "economy"] },
  "cbo-nigeria-history": { eras: ["pre-colonial", "colonial", "independence", "civil-war", "military-rule", "democracy", "reform"] },
  "agenda-2050-npc": { sectors: ["economy", "energy", "education", "governance", "transportation", "real-estate", "tourism"] },
  "un-wpp-2024": { sectors: ["economy", "education", "real-estate", "healthcare", "agriculture"] },
  "nerc-quarterly": { sectors: ["energy", "manufacturing"] },
  "nigeria-etp": { sectors: ["energy"] },
  "nbs-nlfs-2024": { sectors: ["economy", "financial-inclusion"] },
  "world-bank-ndu-2025": { sectors: ["economy", "energy", "education"] },
  "un-world-urbanization-prospects": { sectors: ["real-estate", "economy"] },
  "irena-nigeria-energy": { sectors: ["energy"] },
  "world-bank-electricity-access": { sectors: ["energy"] },
  "world-bank-g7-indicators": { sectors: ["economy", "governance", "energy", "technology", "transportation", "real-estate", "tourism"] },
  "ilo-employment-stats": { sectors: ["economy"] },
  "itu-digital-indicators": { sectors: ["technology"] },
  "wipo-ip-stats": { sectors: ["technology", "creative-economy"] },
  "idea-election-turnout": { sectors: ["governance"] },
  "international-budget-partnership": { sectors: ["governance"] },
  "statehouse-2026-appropriation": { sectors: ["governance", "economy"] },
  "unesco-education-spending": { sectors: ["education"] },
  "who-health-workforce": { sectors: ["healthcare", "education"] },
  "global-peace-index": { sectors: ["security"] },
  "unodc-crime-stats": { sectors: ["security"] },
  "ucdp-conflict-data": { sectors: ["security"] },
  "nigeria-constitution-1999": { sectors: ["governance"] },
  "world-bank-population-total": { sectors: ["economy", "education", "real-estate"] },
  "world-bank-gdp-current-usd": { sectors: ["economy"] },
  "state-house-president-profile": { sectors: ["governance"] },
  "state-house-vice-president-profile": { sectors: ["governance"] },
  ...PHASE2_SOURCE_META,
};

export const SOURCES: Source[] = [
  ...RAW_SOURCES.map((source) => ({
    ...source,
    ...SOURCE_META[source.id],
  })),
  ...ICON_SOURCES,
];

export function getSourceById(id: string): Source | undefined {
  return SOURCES.find((s) => s.id === id);
}

export function getSourcesByIds(ids: string[]): Source[] {
  return ids.map((id) => getSourceById(id)).filter(Boolean) as Source[];
}
