import type { Source } from "@/types/content";
import { PHASE2_RAW_SOURCES, PHASE2_SOURCE_META } from "./phase2/sources";

const RAW_SOURCES: Source[] = [
  {
    id: "world-bank-nigeria-overview",
    title: "Nigeria Economic Overview",
    publisher: "World Bank",
    year: 2024,
    url: "https://www.worldbank.org/en/country/nigeria/overview",
  },
  {
    id: "nbs-gdp-report-2024",
    title: "Nigerian Gross Domestic Product Report Q4 2024",
    publisher: "National Bureau of Statistics (NBS)",
    year: 2025,
    url: "https://www.nigerianstat.gov.ng",
  },
  {
    id: "mckinsey-nigeria-2050",
    title: "Nigeria's Path to Prosperity: Agenda 2050 Scenarios",
    publisher: "McKinsey Global Institute",
    year: 2023,
    url: "https://www.mckinsey.com",
  },
  {
    id: "pwc-nigeria-2050",
    title: "Nigeria in 2050: The Long View",
    publisher: "PwC",
    year: 2024,
    url: "https://www.pwc.com/ng",
  },
  {
    id: "undp-hdi-nigeria",
    title: "Human Development Report — Nigeria",
    publisher: "UNDP",
    year: 2024,
    url: "https://hdr.undp.org",
  },
  {
    id: "unesco-literacy-nigeria",
    title: "Literacy Rates — Sub-Saharan Africa",
    publisher: "UNESCO Institute for Statistics",
    year: 2023,
    url: "https://uis.unesco.org",
  },
  {
    id: "iea-nigeria-energy",
    title: "Nigeria Energy Outlook",
    publisher: "International Energy Agency",
    year: 2024,
    url: "https://www.iea.org",
  },
  {
    id: "gsma-nigeria-digital",
    title: "The Mobile Economy: Nigeria",
    publisher: "GSMA",
    year: 2024,
    url: "https://www.gsma.com",
  },
  {
    id: "transparency-corruption-index",
    title: "Corruption Perceptions Index",
    publisher: "Transparency International",
    year: 2024,
    url: "https://www.transparency.org",
  },
  {
    id: "world-bank-doing-business",
    title: "Ease of Doing Business — Historical Data",
    publisher: "World Bank",
    year: 2020,
    url: "https://archive.doingbusiness.org",
  },
  {
    id: "sipri-security-africa",
    title: "Armed Conflict Survey — West Africa",
    publisher: "SIPRI",
    year: 2024,
    url: "https://www.sipri.org",
  },
  {
    id: "npc-population-projection",
    title: "Population Projection for Nigeria 2023–2050",
    publisher: "National Population Commission",
    year: 2023,
    url: "https://nationalpopulation.gov.ng",
  },
  {
    id: "afdb-industrialization",
    title: "Industrialization Strategy for Africa — Nigeria Case Study",
    publisher: "African Development Bank",
    year: 2023,
    url: "https://www.afdb.org",
  },
  {
    id: "heritage-economic-freedom",
    title: "Index of Economic Freedom — Nigeria",
    publisher: "Heritage Foundation",
    year: 2024,
    url: "https://www.heritage.org",
  },
  {
    id: "cbo-nigeria-history",
    title: "Colonial and Post-Colonial Nigeria: A Historical Overview",
    publisher: "Cambridge University Press (academic reference)",
    year: 2022,
  },
  {
    id: "agenda-2050-npc",
    title: "Nigeria Agenda 2050: Making Nigeria a Top-20 Economy",
    publisher: "National Planning Commission",
    year: 2022,
    url: "https://nationalplanning.gov.ng",
  },
  {
    id: "world-bank-g7-indicators",
    title: "World Development Indicators — G7 Economies",
    publisher: "World Bank",
    year: 2024,
    url: "https://data.worldbank.org",
  },
  {
    id: "ilo-employment-stats",
    title: "ILO Employment and Informal Economy Statistics",
    publisher: "International Labour Organization",
    year: 2023,
    url: "https://ilostat.ilo.org",
  },
  {
    id: "itu-digital-indicators",
    title: "ICT Development Index & Digital Indicators",
    publisher: "International Telecommunication Union",
    year: 2024,
    url: "https://www.itu.int",
  },
  {
    id: "wipo-ip-stats",
    title: "World Intellectual Property Indicators",
    publisher: "WIPO",
    year: 2024,
    url: "https://www.wipo.int",
  },
  {
    id: "idea-election-turnout",
    title: "Voter Turnout Database",
    publisher: "International IDEA",
    year: 2024,
    url: "https://www.idea.int",
  },
  {
    id: "international-budget-partnership",
    title: "Open Budget Survey",
    publisher: "International Budget Partnership",
    year: 2023,
    url: "https://internationalbudget.org",
  },
  {
    id: "unesco-education-spending",
    title: "Education Finance Watch",
    publisher: "UNESCO",
    year: 2024,
    url: "https://www.unesco.org",
  },
  {
    id: "who-health-workforce",
    title: "Global Health Workforce Statistics",
    publisher: "World Health Organization",
    year: 2024,
    url: "https://www.who.int",
  },
  {
    id: "global-peace-index",
    title: "Global Peace Index",
    publisher: "Institute for Economics & Peace",
    year: 2024,
    url: "https://www.visionofhumanity.org",
  },
  {
    id: "unodc-crime-stats",
    title: "UNODC Crime & Criminal Justice Statistics",
    publisher: "United Nations Office on Drugs and Crime",
    year: 2023,
    url: "https://www.unodc.org",
  },
  {
    id: "ucdp-conflict-data",
    title: "UCDP Battle-Related Deaths Dataset",
    publisher: "Uppsala Conflict Data Program",
    year: 2024,
    url: "https://ucdp.uu.se",
  },
  ...PHASE2_RAW_SOURCES,
];

const SOURCE_META: Record<string, Pick<Source, "sectors" | "eras">> = {
  "world-bank-nigeria-overview": { sectors: ["economy", "governance", "energy", "security", "transportation"] },
  "nbs-gdp-report-2024": { sectors: ["economy"] },
  "mckinsey-nigeria-2050": { sectors: ["economy", "technology", "education"] },
  "pwc-nigeria-2050": { sectors: ["economy"] },
  "undp-hdi-nigeria": { sectors: ["education", "security"] },
  "unesco-literacy-nigeria": { sectors: ["education"] },
  "iea-nigeria-energy": { sectors: ["energy"] },
  "gsma-nigeria-digital": { sectors: ["technology"] },
  "transparency-corruption-index": { sectors: ["governance"] },
  "world-bank-doing-business": { sectors: ["economy", "governance"] },
  "sipri-security-africa": { sectors: ["security"], eras: ["civil-war", "military-rule"] },
  "npc-population-projection": { sectors: ["economy", "education"] },
  "afdb-industrialization": { sectors: ["economy", "energy", "transportation"] },
  "heritage-economic-freedom": { sectors: ["governance", "economy"] },
  "cbo-nigeria-history": { eras: ["pre-colonial", "colonial", "independence", "civil-war", "military-rule", "democracy", "reform"] },
  "agenda-2050-npc": { sectors: ["economy", "energy", "education", "governance", "transportation"] },
  "world-bank-g7-indicators": { sectors: ["economy", "governance", "energy", "technology", "transportation"] },
  "ilo-employment-stats": { sectors: ["economy"] },
  "itu-digital-indicators": { sectors: ["technology"] },
  "wipo-ip-stats": { sectors: ["technology"] },
  "idea-election-turnout": { sectors: ["governance"] },
  "international-budget-partnership": { sectors: ["governance"] },
  "unesco-education-spending": { sectors: ["education"] },
  "who-health-workforce": { sectors: ["education"] },
  "global-peace-index": { sectors: ["security"] },
  "unodc-crime-stats": { sectors: ["security"] },
  "ucdp-conflict-data": { sectors: ["security"] },
  ...PHASE2_SOURCE_META,
};

export const SOURCES: Source[] = RAW_SOURCES.map((source) => ({
  ...source,
  ...SOURCE_META[source.id],
}));

export function getSourceById(id: string): Source | undefined {
  return SOURCES.find((s) => s.id === id);
}

export function getSourcesByIds(ids: string[]): Source[] {
  return ids.map((id) => getSourceById(id)).filter(Boolean) as Source[];
}
