#!/usr/bin/env python3
"""Crop icon portraits to a face square; drop statues and images with no detectable face."""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
ICON_DIR = ROOT / "public" / "icons"
MANIFEST = ROOT / "src" / "content" / "icons" / "portraits.ts"
MODEL = ROOT / "scripts" / "models" / "face_detection_yunet_2023mar.onnx"
MODEL_URL = "https://github.com/opencv/opencv_zoo/raw/main/models/face_detection_yunet/face_detection_yunet_2023mar.onnx"
BLOCKED = re.compile(r"statue|monument|equestrian|tomb|grave|mausoleum", re.I)
SIZE = 256
SCORE = 0.55


def parse_manifest() -> dict[str, dict[str, str]]:
    text = MANIFEST.read_text()
    entries: dict[str, dict[str, str]] = {}
    for match in re.finditer(
        r'"([^"]+)": \{\s*src: "([^"]+)",\s*alt: "([^"]*)",\s*credit: "([^"]*)",\s*license: "([^"]*)",\s*sourceUrl: "([^"]*)"',
        text,
    ):
        entries[match.group(1)] = {
            "src": match.group(2),
            "alt": match.group(3),
            "credit": match.group(4),
            "license": match.group(5),
            "sourceUrl": match.group(6),
        }
    return entries


def write_manifest(entries: dict[str, dict[str, str]]) -> None:
    lines = [
        'import type { IconPortrait } from "@/types/content";',
        "",
        "/** Generated by scripts/fetch-icon-portraits.ts — do not edit by hand. */",
        "export const ICON_PORTRAITS: Record<string, IconPortrait> = {",
    ]
    for key, value in entries.items():
        lines.append(f"  {json.dumps(key)}: {{")
        lines.append(f"    src: {json.dumps(value['src'])},")
        lines.append(f"    alt: {json.dumps(value['alt'])},")
        lines.append(f"    credit: {json.dumps(value['credit'])},")
        lines.append(f"    license: {json.dumps(value['license'])},")
        lines.append(f"    sourceUrl: {json.dumps(value['sourceUrl'])},")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    MANIFEST.write_text("\n".join(lines))


def ensure_model() -> Path:
    if MODEL.exists() and MODEL.stat().st_size > 100_000:
        return MODEL
    MODEL.parent.mkdir(parents=True, exist_ok=True)
    print(f"Downloading face model → {MODEL}")
    urllib.request.urlretrieve(MODEL_URL, MODEL)
    return MODEL


def detect_faces(image: np.ndarray, detector: cv2.FaceDetectorYN) -> list[tuple[int, int, int, int]]:
    height, width = image.shape[:2]
    detector.setInputSize((width, height))
    _result, faces = detector.detect(image)
    if faces is None or len(faces) == 0:
        return []
    boxes: list[tuple[int, int, int, int]] = []
    for row in faces:
        x, y, w, h, score = int(row[0]), int(row[1]), int(row[2]), int(row[3]), float(row[-1])
        if score >= SCORE and w > 20 and h > 20:
            boxes.append((x, y, w, h))
    return boxes


def crop_to_face(image: np.ndarray, faces: list[tuple[int, int, int, int]]) -> np.ndarray:
    x, y, w, h = max(faces, key=lambda box: box[2] * box[3])
    height, width = image.shape[:2]
    pad = int(max(w, h) * 0.6)
    cx, cy = x + w // 2, y + int(h * 0.45)
    side = max(w, h) + pad * 2
    x1 = max(0, cx - side // 2)
    y1 = max(0, cy - side // 2)
    x2 = min(width, x1 + side)
    y2 = min(height, y1 + side)
    side = min(x2 - x1, y2 - y1)
    x2, y2 = x1 + side, y1 + side
    crop = image[y1:y2, x1:x2]
    if crop.size == 0:
        return image
    return cv2.resize(crop, (SIZE, SIZE), interpolation=cv2.INTER_AREA)


def main() -> int:
    detector = cv2.FaceDetectorYN_create(str(ensure_model()), "", (320, 320), SCORE, 0.3, 5000)
    manifest = parse_manifest()
    kept: dict[str, dict[str, str]] = {}
    cropped = 0
    dropped = 0

    for path in sorted(ICON_DIR.iterdir()):
        if path.suffix.lower() not in {".jpg", ".jpeg", ".png", ".webp", ".gif"}:
            continue
        icon_id = path.stem
        meta = manifest.get(icon_id, {})
        blob = f"{path.name} {meta.get('sourceUrl', '')} {meta.get('alt', '')}"
        if BLOCKED.search(blob) or icon_id == "queen-amina":
            path.unlink()
            dropped += 1
            print(f"drop  {icon_id} — statue/monument file")
            continue

        image = cv2.imread(str(path), cv2.IMREAD_COLOR)
        if image is None or min(image.shape[:2]) < 80:
            path.unlink(missing_ok=True)
            dropped += 1
            print(f"drop  {icon_id} — unreadable or too small")
            continue

        faces = detect_faces(image, detector)
        if not faces:
            path.unlink()
            dropped += 1
            print(f"drop  {icon_id} — no face detected")
            continue

        cropped_image = crop_to_face(image, faces)
        out_path = path.with_suffix(".jpg")
        cv2.imwrite(str(out_path), cropped_image, [int(cv2.IMWRITE_JPEG_QUALITY), 88])
        if out_path != path:
            path.unlink()
        if icon_id in manifest:
            updated = dict(manifest[icon_id])
            updated["src"] = f"/icons/{out_path.name}"
            kept[icon_id] = updated
        else:
            kept[icon_id] = {
                "src": f"/icons/{out_path.name}",
                "alt": f"Portrait of {icon_id.replace('-', ' ')}",
                "credit": "Wikimedia Commons",
                "license": "See Wikimedia Commons",
                "sourceUrl": "https://commons.wikimedia.org/",
            }
        cropped += 1
        print(f"crop  {icon_id} ({len(faces)} face(s))")

    write_manifest(kept)
    print(f"\nCropped {cropped}, dropped {dropped}, kept in manifest {len(kept)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
