import type { G7BenchmarkMetric } from "@/types/content";

/** G7 benchmark rows for Phase 2 sectors — appended to G7_BENCHMARK_METRICS. */
export const PHASE2_G7_METRICS: G7BenchmarkMetric[] = [
  {
    id: "health-spending-gdp",
    sectorSlug: "healthcare",
    label: "Health Expenditure",
    definition: "Current health expenditure (% of GDP) — WHO Global Health Expenditure Database.",
    unit: "% of GDP",
    referenceYear: 2021,
    nigeria: 3.2,
    g7Countries: { CA: 10.9, FR: 11.1, DE: 11.7, IT: 8.8, JP: 10.9, GB: 10.2, US: 16.8 },
    nigeria2050: 6.5,
    higherIsBetter: true,
    sourceId: "who-nigeria-health",
    sourceSeries: "WHO · SHA · Current expenditure % GDP",
  },
  {
    id: "physicians-density",
    sectorSlug: "healthcare",
    label: "Physicians per 1,000",
    definition: "Medical doctors per 1,000 population — WHO health workforce statistics.",
    unit: "physicians",
    referenceYear: 2021,
    nigeria: 0.38,
    g7Countries: { CA: 2.6, FR: 3.3, DE: 4.3, IT: 4.0, JP: 2.4, GB: 3.0, US: 2.6 },
    nigeria2050: 1.8,
    higherIsBetter: true,
    sourceId: "who-nigeria-health",
    sourceSeries: "WHO · HWF · Physicians per 1,000",
  },
  {
    id: "agriculture-gdp-share",
    sectorSlug: "agriculture",
    label: "Agriculture Value Added",
    definition: "Agriculture, forestry, and fishing (% of GDP) — WDI national accounts.",
    unit: "% of GDP",
    referenceYear: 2022,
    nigeria: 24.1,
    g7Countries: { CA: 1.9, FR: 1.6, DE: 0.8, IT: 2.0, JP: 1.0, GB: 0.8, US: 0.9 },
    higherIsBetter: false,
    sourceId: "fao-nigeria-agriculture",
    sourceSeries: "WDI · NV.AGR.TOTL.ZS",
    context: "Higher share reflects lower industrialization, not stronger food security.",
  },
  {
    id: "undernourishment",
    sectorSlug: "agriculture",
    label: "Prevalence of Undernourishment",
    definition: "Percentage of population undernourished — FAO SOFI harmonized series.",
    unit: "%",
    referenceYear: 2022,
    nigeria: 8.9,
    g7Countries: { CA: 2.5, FR: 2.5, DE: 2.5, IT: 2.5, JP: 2.5, GB: 2.5, US: 2.5 },
    nigeria2050: 2.0,
    higherIsBetter: false,
    sourceId: "fao-nigeria-agriculture",
    sourceSeries: "FAO · SN · Undernourishment",
  },
  {
    id: "creative-exports",
    sectorSlug: "creative-economy",
    label: "Charges for IP & Services Exports",
    definition: "Charges for the use of intellectual property, receipts (% of total exports) — proxy for creative/services exports.",
    unit: "% of exports",
    referenceYear: 2022,
    nigeria: 0.4,
    g7Countries: { CA: 1.8, FR: 2.9, DE: 2.1, IT: 1.5, JP: 3.2, GB: 4.8, US: 5.1 },
    nigeria2050: 3.5,
    higherIsBetter: true,
    sourceId: "unesco-creative-economy",
    sourceSeries: "WDI · BX.GSR.ROYL.ZS",
  },
  {
    id: "manufacturing-employment",
    sectorSlug: "manufacturing",
    label: "Industry Employment Share",
    definition: "Employment in industry (% of total employment) — ILO modelled estimates.",
    unit: "%",
    referenceYear: 2022,
    nigeria: 12.4,
    g7Countries: { CA: 19.2, FR: 18.5, DE: 24.8, IT: 20.1, JP: 20.5, GB: 17.8, US: 19.4 },
    nigeria2050: 22,
    higherIsBetter: true,
    sourceId: "unido-manufacturing",
    sourceSeries: "ILO · EMP INDUSTRY",
  },
  {
    id: "bank-account-ownership",
    sectorSlug: "financial-inclusion",
    label: "Account Ownership",
    definition: "Adults with an account at a financial institution or mobile-money provider — Global Findex.",
    unit: "%",
    referenceYear: 2021,
    nigeria: 45,
    g7Countries: { CA: 99, FR: 99, DE: 99, IT: 86, JP: 98, GB: 97, US: 95 },
    nigeria2050: 95,
    higherIsBetter: true,
    sourceId: "world-bank-financial-inclusion",
    sourceSeries: "Global Findex · Account ownership",
  },
  {
    id: "digital-payments",
    sectorSlug: "financial-inclusion",
    label: "Made or Received Digital Payment",
    definition: "Adults who made or received a digital payment in the past year — Global Findex.",
    unit: "%",
    referenceYear: 2021,
    nigeria: 38,
    g7Countries: { CA: 96, FR: 95, DE: 90, IT: 82, JP: 82, GB: 97, US: 89 },
    nigeria2050: 92,
    higherIsBetter: true,
    sourceId: "world-bank-financial-inclusion",
    sourceSeries: "Global Findex · Digital payments",
  },
];
