import type { G7BenchmarkMetric } from "@/types/content";

/** G7 benchmark rows for Phase 2 sectors, appended to G7_BENCHMARK_METRICS. */
export const PHASE2_G7_METRICS: G7BenchmarkMetric[] = [
  {
    id: "health-spending-gdp",
    sectorSlug: "healthcare",
    label: "Health Expenditure",
    definition: "Current health expenditure (% of GDP), WHO Global Health Expenditure Database.",
    unit: "% of GDP",
    referenceYear: 2021,
    nigeria: 3.2,
    g7Countries: { CA: 10.9, FR: 11.1, DE: 11.7, IT: 8.8, JP: 10.9, GB: 10.2, US: 16.8 },
    nigeria2050: 6.5,
    higherIsBetter: true,
    sourceId: "who-nigeria-health",
    sourceSeries: "WHO · SHA · Current expenditure % GDP",
  },
  {
    id: "physicians-density",
    sectorSlug: "healthcare",
    label: "Physicians per 1,000",
    definition: "Medical doctors per 1,000 population, WHO health workforce statistics.",
    unit: "physicians",
    referenceYear: 2021,
    nigeria: 0.38,
    g7Countries: { CA: 2.6, FR: 3.3, DE: 4.3, IT: 4.0, JP: 2.4, GB: 3.0, US: 2.6 },
    nigeria2050: 1.8,
    higherIsBetter: true,
    sourceId: "who-nigeria-health",
    sourceSeries: "WHO · HWF · Physicians per 1,000",
  },
  {
    id: "agriculture-gdp-share",
    sectorSlug: "agriculture",
    label: "Agriculture Value Added",
    definition: "Agriculture, forestry, and fishing (% of GDP). WDI national accounts.",
    unit: "% of GDP",
    referenceYear: 2022,
    nigeria: 24.1,
    g7Countries: { CA: 1.9, FR: 1.6, DE: 0.8, IT: 2.0, JP: 1.0, GB: 0.8, US: 0.9 },
    higherIsBetter: false,
    sourceId: "fao-nigeria-agriculture",
    sourceSeries: "WDI · NV.AGR.TOTL.ZS",
    context: "A higher share often tracks lower industrialization rather than stronger food security.",
  },
  {
    id: "undernourishment",
    sectorSlug: "agriculture",
    label: "Prevalence of Undernourishment",
    definition: "Percentage of population undernourished. FAO SOFI harmonized series.",
    unit: "%",
    referenceYear: 2022,
    nigeria: 8.9,
    g7Countries: { CA: 2.5, FR: 2.5, DE: 2.5, IT: 2.5, JP: 2.5, GB: 2.5, US: 2.5 },
    nigeria2050: 2.0,
    higherIsBetter: false,
    sourceId: "fao-nigeria-agriculture",
    sourceSeries: "FAO · SN · Undernourishment",
  },
  {
    id: "creative-exports",
    sectorSlug: "creative-economy",
    label: "Charges for IP & Services Exports",
    definition: "Charges for the use of intellectual property, receipts (% of total exports), proxy for creative/services exports.",
    unit: "% of exports",
    referenceYear: 2022,
    nigeria: 0.4,
    g7Countries: { CA: 1.8, FR: 2.9, DE: 2.1, IT: 1.5, JP: 3.2, GB: 4.8, US: 5.1 },
    nigeria2050: 3.5,
    higherIsBetter: true,
    sourceId: "unesco-creative-economy",
    sourceSeries: "WDI · BX.GSR.ROYL.ZS",
  },
  {
    id: "manufacturing-employment",
    sectorSlug: "manufacturing",
    label: "Industry Employment Share",
    definition: "Employment in industry (% of total employment). ILO modelled estimates.",
    unit: "%",
    referenceYear: 2022,
    nigeria: 12.4,
    g7Countries: { CA: 19.2, FR: 18.5, DE: 24.8, IT: 20.1, JP: 20.5, GB: 17.8, US: 19.4 },
    nigeria2050: 22,
    higherIsBetter: true,
    sourceId: "unido-manufacturing",
    sourceSeries: "ILO · EMP INDUSTRY",
  },
  {
    id: "bank-account-ownership",
    sectorSlug: "financial-inclusion",
    label: "Account Ownership",
    definition: "Adults with an account at a financial institution or mobile-money provider. Global Findex.",
    unit: "%",
    referenceYear: 2021,
    nigeria: 45,
    g7Countries: { CA: 99, FR: 99, DE: 99, IT: 86, JP: 98, GB: 97, US: 95 },
    nigeria2050: 95,
    higherIsBetter: true,
    sourceId: "world-bank-financial-inclusion",
    sourceSeries: "Global Findex · Account ownership",
  },
  {
    id: "digital-payments",
    sectorSlug: "financial-inclusion",
    label: "Made or Received Digital Payment",
    definition: "Adults who made or received a digital payment in the past year. Global Findex.",
    unit: "%",
    referenceYear: 2021,
    nigeria: 38,
    g7Countries: { CA: 96, FR: 95, DE: 90, IT: 82, JP: 82, GB: 97, US: 89 },
    nigeria2050: 92,
    higherIsBetter: true,
    sourceId: "world-bank-financial-inclusion",
    sourceSeries: "Global Findex · Digital payments",
  },
  {
    id: "lpi-overall",
    sectorSlug: "transportation",
    label: "Logistics Performance Index",
    definition:
      "World Bank LPI overall score (1 = low, 5 = high), 2023 international survey wave, same release for Nigeria and all G7 members.",
    unit: "score 1–5",
    referenceYear: 2023,
    nigeria: 2.6,
    g7Countries: { CA: 4.0, FR: 3.9, DE: 4.1, IT: 3.7, JP: 3.9, GB: 3.7, US: 3.8 },
    nigeria2050: 3.5,
    higherIsBetter: true,
    sourceId: "world-bank-lpi",
    sourceSeries: "World Bank · LPI 2023 overall score",
    context:
      "Transcribed from the 2023 LPI global table (Nigeria rank 88). The 2050 figure is a Naija2050 scenario.",
  },
  {
    id: "air-passengers-per-1000",
    sectorSlug: "transportation",
    label: "Air Passengers per 1,000 People",
    definition:
      "Air transport passengers carried (WDI IS.AIR.PSGR) divided by population (SP.POP.TOTL), × 1,000, 2019, latest pre-pandemic common year. Counts passengers on carriers registered in that country.",
    unit: "per 1,000 people",
    referenceYear: 2019,
    nigeria: 31,
    g7Countries: { CA: 2482, FR: 1058, DE: 1319, IT: 465, JP: 1028, GB: 2137, US: 2806 },
    nigeria2050: 400,
    higherIsBetter: true,
    sourceId: "world-bank-g7-indicators",
    sourceSeries: "WDI · IS.AIR.PSGR / SP.POP.TOTL · 2019 (API retrieved 18 Aug 2026)",
    context:
      "Nigeria 6.54M passengers / 209.5M people. A 2050 scenario of 400 per 1,000 would still sit below Italy's 2019 level (465).",
  },
  {
    id: "road-traffic-deaths",
    sectorSlug: "transportation",
    label: "Road Traffic Death Rate",
    definition:
      "WHO-estimated road traffic deaths per 100,000 population. Global Status Report on Road Safety 2023, 2021 modelled year for Nigeria and all G7 members.",
    unit: "per 100k",
    referenceYear: 2021,
    nigeria: 17.2,
    g7Countries: { CA: 4.7, FR: 4.7, DE: 3.3, IT: 5.0, JP: 2.7, GB: 2.4, US: 14.2 },
    nigeria2050: 8.0,
    higherIsBetter: false,
    sourceId: "who-road-safety",
    sourceSeries: "WHO · GSRRS 2023 · estimated rate per 100,000 (2021)",
    context:
      "Lower is better. Nigeria country profile: 17.2 (2021). United States profile: 14.2 (2021). The 2050 figure is a scenario.",
  },
  {
    id: "urban-slum-share",
    sectorSlug: "real-estate",
    label: "Urban Population in Slums",
    definition:
      "Population living in slums (% of urban population). UN-Habitat / World Bank WDI EN.POP.SLUM.UR.ZS, 2022 latest common year for Nigeria and all G7 members.",
    unit: "%",
    referenceYear: 2022,
    nigeria: 48.5,
    g7Countries: { CA: 1.1, FR: 0, DE: 0, IT: 0.02, JP: 2.0, GB: 0.16, US: 0.09 },
    nigeria2050: 25,
    higherIsBetter: false,
    sourceId: "world-bank-g7-indicators",
    sourceSeries: "WDI · EN.POP.SLUM.UR.ZS · 2022 (API retrieved 18 Aug 2026)",
    context:
      "This is the housing-quality gap. National density is not: Nigeria (250/km²) is already in Germany's range. The 2050 figure is a scenario.",
  },
  {
    id: "urban-population-share",
    sectorSlug: "real-estate",
    label: "Urban Population Share",
    definition:
      "Urban population (% of total population). WDI SP.URB.TOTL.IN.ZS, 2023 for Nigeria and all G7 members.",
    unit: "%",
    referenceYear: 2023,
    nigeria: 62.2,
    g7Countries: { CA: 82.5, FR: 78.8, DE: 81.9, IT: 69.5, JP: 92.1, GB: 83.2, US: 80.1 },
    nigeria2050: 70,
    higherIsBetter: true,
    sourceId: "world-bank-g7-indicators",
    sourceSeries: "WDI · SP.URB.TOTL.IN.ZS · 2023 (API retrieved 18 Aug 2026)",
    context:
      "Nigeria is less urban than the G7, so housing demand will keep rising as people move to cities. Higher urban share is not automatically better housing; without supply it raises rents.",
  },
  {
    id: "unesco-world-heritage-count",
    sectorSlug: "tourism",
    label: "UNESCO World Heritage Properties",
    definition:
      "Properties inscribed on the UNESCO World Heritage List, counted by State Party. Same list, same session, for Nigeria and all G7 members.",
    unit: "sites",
    referenceYear: 2025,
    nigeria: 2,
    g7Countries: { CA: 22, FR: 54, DE: 55, IT: 61, JP: 26, GB: 35, US: 26 },
    nigeria2050: 6,
    higherIsBetter: true,
    sourceId: "unesco-world-heritage",
    sourceSeries: "UNESCO WHC · properties by State Party · after 47th session (July 2025)",
    context:
      "Nigeria: Sukur (1999) and Osun-Osogbo (2005). WDI tourism receipts for 2019 omit Canada and the UK, so this site does not publish a G7 receipts row. The 2050 figure is a scenario.",
  },
];
